/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.awt.AWTException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, MalformedURLException, AWTException {
        
        // This is to remove unnecessary warnings from your console
        System.setProperty("java.util.logging.config.file", "logging.properties");
        
       
     
              Image_Url ImageTest = new Image_Url();                    // Initialize your Image_Url class
   
        //TODO: call your test case functions one after other here


             
          ImageTest.Image_Url();              //call your test case functions one after other here
          


        //END Tests

        
              
          ImageTest.endTest();              //End your test by clearning connections and closing browse
       
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException, AWTException {
        new App().getGreeting();
    }
    
}
